language: python

python:
  - "2.7"
  - "3.5"
  - "pypy"

install:
  - pip install .
  - pip install -r requirements/test.txt

script:
  - nosetests test

branches:
  only:
    - master
    - repo-split
    - /^v\d+\.\d+\.\d+.*$/

before_deploy:
  - python setup.py sdist bdist_wheel

deploy:
  provider: releases
  api_key:
    secure: lDCG7T0CTzKhFk5QNwaI6d+DyJcB44ZLrMpqsHKJ84ez4G/NG7o06obS9qXxU/SXHrWJsYnoDZEd6rg72lrHw0XJcuftQB3Vc8Fv4d+tMXoNnsxkiD10c4sfoXh9iNW6D3phqA8LBARa2hBFB6L4gdr5yOgKcba13EAEvDMT1YEIyw4pUP6nJZLWx+fS2Cx9uNKTHMU2461NM+opU9ejCtLEmSE1FoolqSx/k0eFKGcpz7VvINKwPyQhxrLjWw6YFOfOsu8MC8XNTQqjCJ3rnee3z7M3/iN5cKIcBQFkcsPJRQ6Gh3vyWzP3q8SqyC1oWUALXRhDjDsh3iy+JrxhcX+FwQPBoBqfChqriWFBN46vZwN8Pv44U8whFBqXj6RGKgMv9fFjsrKFDla5Rx1QbqnVIVZihfMuSCVFl8PUdQeoXJSzjYJ7cT1EXPsfAyNoU4U2gr6Wtw6drwNHqYRNfVsvnwA/UTjFvqvjTYqRGchyNhtuPGqpD0fn2jgEDddGMssMh1GxlCRkhfYPMpwDibdUERt9nFWTEcXgrt/kinphRUHXFIL2PFLwzWQN9Ks5VKCtE4hXncGa023Y53ue6Tgz5pLQ+BoG7LGSsH9YO8jpuJeCNtTfQHPWgbfl1Anlrz6MLb5EkQniSZD8vDHMiEDUdbG3hrQeH/DDm3pKGrU=
  file_glob: true
  file: frog-*.whl
  skip_cleanup: false
  on:
    tags: true
