language: python

python:
  - "2.7"
  - "3.5"
  - "pypy"

install:
  - pip install .
  - pip install -r requirements/test.txt

script:
  - nosetests test

branches:
  only:
    - master
    - repo-split
    - /^v\d+\.\d+\.\d+.*$/

before_deploy:
  - python setup.py sdist bdist_wheel

deploy:
  provider: releases
  api_key:
    secure: OhDjVKDjGBXoPPpCs+fFWRICaNJJ4vaGudojrvTo4SmJJeENJnarAvkd2rJq/TEGSN/8Ym/GjLaAXkl9MhtRE6+25T54zqJ3oaSZIq+7pifhx7iRsYgakPTlBXm0E8jxeMV/Fxg6RJuKmY0VeMAG7b6ac6FNNI0t2saPHUWtLsxltU9VtH8tuUHPgUpTxT7YYDCW97Y1dBnOxlf+wKP78jaMMjYK49W+j1v8cyXsMMVIbacC6z1XuHXTBJLXpBjm5XVQJx2WZYKxkJRuKsEsCNOKjRn7z4dg3cnHXbScNlZRBDsE2LXi/4d2Eu3zM9ftyHuNmWcj4A/8uTbDvQK8vEjzZhilNtCcNJgFuV0/gmxEQicFdUQ3Zyi7zLwEXtER4yNPAY1Yz6DBMde/paRr4K/+Jtye3W/v6cmpjT+Mb363IuRxi6q4Se0knHfbAEQ/+Cy0c7NEB9D0iILupPDH3fGiOBsOFSbsJVLgJ/lhewSuU2AuOfSiHPYMbLcWOs3g7v6g15k2sK0NHEatfvxYbp0zKtub1JtMiDEBcwF5B9SGHkqy0FWSwAKp/ZWb/1+Ln2Oc4IR+h1IOppQbC7cyb+Ezn1E7AesXQVna6UUM1/duO1hPQCa+QBn1VJDOzND4Zu4VVLaKmHefAf4AcsqLjE5TlfYPw+IrrFYhNpv1+4o=
  file_glob: true
  file: frog-*.whl
  skip_cleanup: true
  on:
    tags: true
